from .serializers_antigos import *
from .professores import *
from .file import *
from .usuario import *
from .tcc_status import *
from .avaliacao import *
from .tcc_estatico import *
from .banca import *
from .sessoes import *
from .tcc import *
from .semestre import *
from .semestreCoordenador import *