# Generated by Django 5.0.3 on 2024-04-16 00:33

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas_orientador', models.FloatField()),
                ('notas_avaliador1', models.FloatField()),
                ('notas_avaliador2', models.FloatField()),
                ('media_final', models.FloatField()),
                ('ficha_avaliacao', models.FileField(blank=True, null=True, upload_to='avaliacoes/fichas')),
                ('data_avaliacao', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=255, verbose_name='cpf')),
                ('email', models.EmailField(max_length=254)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255)),
                ('presencial', models.BooleanField()),
                ('parecer_orientador', models.TextField(blank=True, null=True)),
                ('parecer_coordenador', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StatusCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aprovacao', models.BooleanField(default=False)),
                ('justificativa', models.CharField(blank=True, max_length=255, null=True)),
                ('dataStatus', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
                ('matricula', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
                ('area', models.CharField(blank=True, max_length=255, null=True)),
                ('grau_academico', models.CharField(blank=True, max_length=255, null=True)),
                ('titulos', models.TextField(blank=True, max_length=255, null=True)),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status_cadastro', to='app.statuscadastro')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(default='2024/1', max_length=255, verbose_name='Período')),
                ('dataAberturaSemestre', models.DateField(default=datetime.datetime.today)),
                ('dataFechamentoSemestre', models.DateField(default=datetime.datetime.today)),
                ('dataAberturaPrazoPropostas', models.DateField(default=datetime.datetime.today)),
                ('dataFechamentoPrazoPropostas', models.DateField(default=datetime.datetime.today)),
                ('configuracoes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.configuracoes')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessaoFinal',
            fields=[
                ('sessao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.sessao')),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.avaliacao')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.sessao',),
        ),
        migrations.CreateModel(
            name='SessaoPrevia',
            fields=[
                ('sessao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.sessao')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.sessao',),
        ),
        migrations.CreateModel(
            name='Banca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.sessao')),
                ('professores', models.ManyToManyField(to='app.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('dataSubmissaoProposta', models.DateTimeField(auto_now_add=True)),
                ('documentoTCC', models.FileField(blank=True, null=True, upload_to='tcc/documento')),
                ('autorizacaoPublicacao', models.FileField(blank=True, null=True, upload_to='tcc/autorizacaoPublicacao')),
                ('dataInicio', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('prazoEntregaPrevia', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('prazoEntregaFinal', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.semestre')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estudante')),
                ('coorientador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coorientador', to='app.professor')),
                ('orientador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientador', to='app.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='tcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tcc'),
        ),
        migrations.CreateModel(
            name='TccStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSTA_ANALISE_PROFESSOR', 'Proposta Analise Professor'), ('PROPOSTA_RECUSADA_PROFESSOR', 'Proposta Recusada Professor'), ('PROPOSTA_ANALISE_COORDENADOR', 'Proposta Analise Coordenador'), ('PROPOSTA_RECUSADA_COORDENADOR', 'Proposta Recusada Coordenador'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('PREVIA', 'Previa'), ('REPROVADO_PREVIA', 'Reprovado Previa'), ('FINAL', 'Final'), ('REPROVADO_FINAL', 'Reprovado Final'), ('AJUSTE', 'Ajuste'), ('APROVADO', 'Aprovado')], max_length=255)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('dataStatus', models.DateTimeField(auto_now=True)),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tcc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProfessorExterno',
            fields=[
                ('professor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.professor')),
                ('identidade', models.FileField(blank=True, null=True, upload_to='professoresExterno/identidade')),
                ('diploma', models.FileField(blank=True, null=True, upload_to='professoresExterno/diploma')),
                ('dataStatus', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.professor',),
        ),
        migrations.CreateModel(
            name='ProfessorInterno',
            fields=[
                ('professor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.professor')),
                ('matricula', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.professor',),
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(max_length=500)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BancaPrioridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banca', models.ManyToManyField(to='app.banca')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SemestreCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAlteracao', models.DateField(auto_now_add=True)),
                ('semestre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.semestre')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professorinterno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atendimento', to='app.professorinterno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='configuracoes',
            name='coordenadorAtual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professorinterno'),
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('justificativaRecusa', models.TextField(blank=True, null=True)),
                ('dataConvite', models.DateTimeField(auto_now_add=True)),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tcc')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
            ],
            options={
                'unique_together': {('professor', 'tcc')},
            },
        ),
    ]
