# Generated by Django 5.0.3 on 2024-03-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notas_orientador', models.FloatField()),
                ('notas_avaliador1', models.FloatField()),
                ('notas_avaliador2', models.FloatField()),
                ('media_final', models.FloatField()),
                ('ficha_avaliacao', models.FileField(upload_to='avaliacoes/fichas')),
                ('data_avaliacao', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=255, verbose_name='cpf')),
                ('email', models.EmailField(max_length=254)),
                ('dataCadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrauAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=255)),
                ('presencial', models.BooleanField()),
                ('parecer_orientador', models.TextField(blank=True, null=True)),
                ('parecer_coordenador', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_termino', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tcc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('dataSubmissaoProposta', models.DateTimeField(auto_now_add=True)),
                ('documentoTCC', models.FileField(upload_to='tcc/documento')),
                ('autorizacaoPublicacao', models.FileField(upload_to='tcc/autorizacaoPublicacao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
            ],
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.usuario')),
                ('area', models.CharField(max_length=255)),
                ('grau_academico', models.CharField(max_length=255)),
                ('titulos', models.TextField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('app.usuario',),
        ),
        migrations.CreateModel(
            name='SessaoFinal',
            fields=[
                ('sessao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='app.sessao')),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='app.avaliacao')),
            ],
            options={
                'abstract': False,
            },
            bases=('app.sessao',),
        ),
        migrations.CreateModel(
            name='StatusTCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Proposta em Análise', 'Proposta Analise'), ('Proposta Recusada', 'Proposta Recusada'), ('TCC em Desenvolvimento', 'Desenvovimento'), ('Aguardando Sessão Prévia', 'Previa'), ('Reprovado na Sessão Prévia', 'Reprovado Previa'), ('Aguardando Sessão Final', 'Final'), ('Reprovado na Sessão Final', 'Reprovado Final'), ('TCC em Fase de Ajuste', 'Ajuste'), ('TCC Aprovado', 'Aprovado')], max_length=255)),
                ('dataStatus', models.DateTimeField(auto_now=True)),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tcc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sessao',
            name='tcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tcc'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.estudante'),
        ),
        migrations.CreateModel(
            name='ProfessorInterno',
            fields=[
                ('professor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.professor')),
                ('matricula', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.professor',),
        ),
        migrations.AddField(
            model_name='tcc',
            name='coorientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coorientador', to='app.professor'),
        ),
        migrations.AddField(
            model_name='tcc',
            name='orientador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orientador', to='app.professor'),
        ),
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('justificativa', models.CharField(max_length=255, verbose_name='Justificativa')),
                ('status', models.CharField(choices=[('Convite em Análise', 'Analise'), ('Convite Aceito', 'Aceito'), ('Convite Recusado', 'Recusado')], default='Convite em Análise', max_length=255, verbose_name='Status')),
                ('dataConvite', models.DateTimeField(auto_now_add=True)),
                ('dataStatus', models.DateTimeField(auto_now=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HorarioAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios_atendimento', to='app.professorinterno')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordenadorAtual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professorinterno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
