# Generated by Django 4.2.6 on 2024-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='grau_academico',
            field=models.CharField(blank=True, choices=[('TECNICO', 'Tecnico'), ('GRADUACAO', 'Graduacao'), ('POSGRADUACAO', 'Posgraduacao'), ('MESTRADO', 'Mestrado'), ('DOUTORADO', 'Doutorado'), ('POSDOUTORADO', 'Posdoutorado')], max_length=255, null=True),
        ),
    ]
