# Generated by Django 5.0.3 on 2024-04-18 02:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tcc',
            name='prazoEntregaFinal',
        ),
        migrations.RemoveField(
            model_name='tcc',
            name='prazoEntregaPrevia',
        ),
        migrations.AddField(
            model_name='banca',
            name='autorSugestao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario'),
        ),
        migrations.AddField(
            model_name='banca',
            name='dataSugestao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='banca',
            name='professoresSugeridos',
            field=models.ManyToManyField(related_name='banca_professores_sugeridos', to='app.professor'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='documentoTCCSessao',
            field=models.FileField(blank=True, null=True, upload_to='sessao/documento'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='prazoEntregaDocumento',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='banca',
            name='professores',
            field=models.ManyToManyField(related_name='banca_professores', to='app.professor'),
        ),
    ]
