# Generated by Django 5.0.3 on 2024-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professorexterno',
            name='statusCadastro',
        ),
        migrations.AlterField(
            model_name='professorexterno',
            name='diploma',
            field=models.FileField(null=True, upload_to='professoresExterno/diploma'),
        ),
        migrations.AlterField(
            model_name='professorexterno',
            name='identidade',
            field=models.FileField(null=True, upload_to='professoresExterno/identidade'),
        ),
    ]
