# Generated by Django 5.0.3 on 2024-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_professorexterno_statuscadastro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professorexterno',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to='professoresExterno/diploma'),
        ),
        migrations.AlterField(
            model_name='professorexterno',
            name='identidade',
            field=models.FileField(blank=True, null=True, upload_to='professoresExterno/identidade'),
        ),
    ]
