# Generated by Django 4.2.6 on 2024-04-08 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_statustcc_tcc_alter_professorexterno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('justificativaRecusa', models.TextField(blank=True, null=True)),
                ('dataConvite', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tcc')),
            ],
            options={
                'unique_together': {('professor', 'tcc')},
            },
        ),
    ]
