# Generated by Django 5.0.3 on 2025-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_tcc_datainicio_superadmin'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superadmin',
            name='nome',
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='email',
            field=models.EmailField(help_text='Endereço de email único usado como identificador principal.', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos aos quais o SuperAdmin pertence.', related_name='superadmin_groups', to='auth.group', verbose_name='Grupos'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permissões específicas do SuperAdmin.', related_name='superadmin_permissions', to='auth.permission', verbose_name='Permissões'),
        ),
        migrations.AlterField(
            model_name='superadmin',
            name='username',
            field=models.CharField(blank=True, help_text='Relacionado ao email. Não é usado diretamente para login.', max_length=150, null=True),
        ),
    ]
