# Generated by Django 5.0.3 on 2024-04-18 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_tcc_prazoentregafinal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='autorSugestao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario'),
        ),
        migrations.AlterField(
            model_name='banca',
            name='professores',
            field=models.ManyToManyField(blank=True, null=True, related_name='banca_professores', to='app.professor'),
        ),
        migrations.AlterField(
            model_name='banca',
            name='professoresSugeridos',
            field=models.ManyToManyField(blank=True, null=True, related_name='banca_professores_sugeridos', to='app.professor'),
        ),
    ]
