# Generated by Django 5.0.3 on 2025-01-19 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_superadmin_nome_alter_superadmin_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='user',
            field=models.OneToOneField(help_text='Relação com o modelo User para autenticação e tokens.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='superadmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
