# Generated by Django 5.0.3 on 2024-04-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_banca_autorsugestao_alter_banca_professores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='grau_academico',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='area',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='titulos',
        ),
        migrations.AddField(
            model_name='professor',
            name='area_atuacao',
            field=models.CharField(blank=True, choices=[('MATEMATICA', 'Matematica'), ('PROBABILIDADE E ESTATISTICA', 'Probabilidade E Estatistica'), ('CIENCIA DA COMPUTACAO', 'Ciencia Da Computacao'), ('ASTRONOMIA', 'Astronomia'), ('FISICA', 'Fisica'), ('QUIMICA', 'Quimica'), ('GEOCIENCIAS', 'Geociencias'), ('BIOLOGIA GERAL', 'Biologia Geral'), ('BIOQUIMICA', 'Bioquimica'), ('FISIOLOGIA', 'Fisiologia'), ('GENETICA', 'Genetica'), ('BOTANICA', 'Botanica'), ('ZOOLOGIA', 'Zoologia'), ('ECOLOGIA', 'Ecologia'), ('MORFOLOGIA', 'Morfologia'), ('PARASITOLOGIA', 'Parasitologia'), ('MICROBIOLOGIA', 'Microbiologia'), ('IMUNOLOGIA', 'Imunologia'), ('FARMACOLOGIA', 'Farmacologia'), ('ODONTOLOGIA', 'Odontologia'), ('MEDICINA', 'Medicina'), ('BIOFISICA', 'Biofisica'), ('PSICOBIOLOGIA', 'Psicobiologia'), ('ENGENHARIA CIVIL', 'Engenharia Civil'), ('ENGENHARIA DE MINAS', 'Engenharia De Minas'), ('ENGENHARIA DE MATERIAIS E METALURGICA', 'Engenharia De Materiais E Metalurgica'), ('ENGENHARIA ELETRICA', 'Engenharia Eletrica'), ('ENGENHARIA MECANICA', 'Engenharia Mecanica'), ('ENGENHARIA QUIMICA', 'Engenharia Quimica'), ('ENGENHARIA SANITARIA', 'Engenharia Sanitaria'), ('ENGENHARIA DE PRODUCAO', 'Engenharia De Producao'), ('ENGENHARIA NUCLEAR', 'Engenharia Nuclear'), ('ENGENHARIA DE TRANSPORTES', 'Engenharia De Transportes'), ('ENGENHARIA NAVAL', 'Engenharia Naval'), ('ENGENHARIA AEROESPACIAL', 'Engenharia Aeroespacial'), ('ENGENHARIA BIOMEDICA', 'Engenharia Biomedica'), ('ENGENHARIA DE PESCA', 'Engenharia De Pesca'), ('OCEANOGRAFIA', 'Oceanografia'), ('CIENCIA E TECNOLOGIA DE ALIMENTOS', 'Ciencia E Tecnologia De Alimentos'), ('NUTRICAO', 'Nutricao'), ('SAUDE COLETIVA', 'Saude Coletiva'), ('ENFERMAGEM', 'Enfermagem'), ('FARMACIA', 'Farmacia'), ('VETERINARIA', 'Veterinaria'), ('AGRONOMIA', 'Agronomia'), ('RECURSOS FLORESTAIS E ENGENHARIA FLORESTAL', 'Recursos Florestais E Engenharia Florestal'), ('ENGENHARIA AGRICOLA', 'Engenharia Agricola'), ('ZOOTECNIA', 'Zootecnia'), ('ECONOMIA DOMESTICA', 'Economia Domestica'), ('DESENHO INDUSTRIAL', 'Desenho Industrial'), ('ARQUITETURA E URBANISMO', 'Arquitetura E Urbanismo'), ('PLANEJAMENTO URBANO E REGIONAL', 'Planejamento Urbano E Regional'), ('DEMOGRAFIA', 'Demografia'), ('CIENCIA DA INFORMACAO', 'Ciencia Da Informacao'), ('MUSEOLOGIA', 'Museologia'), ('COMUNICACAO', 'Comunicacao'), ('SERVICO SOCIAL', 'Servico Social'), ('ECONOMIA', 'Economia'), ('ADMINISTRACAO', 'Administracao'), ('CIENCIA CONTABEIS', 'Ciencia Contabeis'), ('TURISMO', 'Turismo'), ('DIREITO', 'Direito'), ('EDUCACAO', 'Educacao'), ('FILOSOFIA', 'Filosofia'), ('SOCIOLOGIA', 'Sociologia'), ('ANTROPOLOGIA', 'Antropologia'), ('CIENCIA POLITICA', 'Ciencia Politica'), ('TEOLOGIA', 'Teologia'), ('HISTORIA', 'Historia'), ('GEOGRAFIA', 'Geografia'), ('PSICOLOGIA', 'Psicologia'), ('ARTES', 'Artes'), ('LETRAS', 'Letras'), ('LINGUISTICA', 'Linguistica'), ('INTERDISCIPLINAR', 'Interdisciplinar'), ('ENSINO', 'Ensino'), ('MATERIAIS', 'Materiais'), ('BIOTECNOLOGIA', 'Biotecnologia'), ('CIENCIAS AMBIENTAIS', 'Ciencias Ambientais')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='area_interesse',
            field=models.CharField(blank=True, choices=[('Algoritmos, Combinatória e Otimização', 'Algoritmos Combinatoria E Otimizacao'), ('Arquitetura de Computadores e Processamento de Alto Desempenho', 'Arquitetura De Computadores E Processamento De Alto Desempenho'), ('Banco de Dados', 'Banco De Dados'), ('Biologia Computacional', 'Biologia Computacional'), ('Computação Aplicada à Saúde', 'Computacao Aplicada A Saude'), ('Computação Gráfica e Processamento de Imagens', 'Computacao Grafica E Processamento De Imagens'), ('Computação Musical', 'Computacao Musical'), ('Computação Ubíqua e Pervasiva', 'Computacao Ubiqua E Pervasiva'), ('Concepção de Circuitos Integrados', 'Concepcao De Circuitos Integrados'), ('Engenharia de Software', 'Engenharia De Software'), ('Geo Informática', 'Geo Informatica'), ('Informática na Educação', 'Informaticia Na Educacao'), ('Inteligência Artificial', 'Inteligencia Artificial'), ('Inteligência Computacional', 'Inteligencia Computacional'), ('Interação Humano Computador', 'Interacao Humano Computador'), ('International Association for Pattern Recognition (IAPR)', 'Iapr'), ('Jogos e Entretenimento', 'Jogos E Entretenimento'), ('Linguagens de Programação', 'Linguagens De Programacao'), ('Métodos Formais', 'Metodos Formais'), ('Processamento de Linguagem Natural', 'Processamento De Linguagem Natural'), ('Realidade Virtual', 'Realidade Virtual'), ('Redes de Computadores e Sistemas Distribuídos', 'Redes De Computadores E Sistemas Distribuidos'), ('Robótica', 'Robotica'), ('Segurança', 'Seguranca'), ('Sistemas Colaborativos', 'Sistemas Colaborativos'), ('Sistemas de Informação', 'Sistemas De Informacao'), ('Sistemas Multimídia e Hipermídia', 'Sistemas Multimidia E Hipermidia'), ('Sistemas Tolerantes a Falhas', 'Sistemas Tolerantes A Falhas')], max_length=255, null=True),
        ),
    ]
