# Generated by Django 4.2.6 on 2024-03-31 03:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('app', '0003_alter_professorexterno_diploma_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professorexterno',
            options={},
        ),
        migrations.RenameField(
            model_name='semestre',
            old_name='settings',
            new_name='configuracoes',
        ),
        migrations.AddField(
            model_name='sessao',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='area',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='grau_academico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='titulos',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='dataAberturaSemestre',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='dataFechamentoSemestre',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='statustcc',
            name='status',
            field=models.CharField(choices=[('Proposta em Análise', 'Proposta Analise'), ('Proposta Recusada', 'Proposta Recusada'), ('TCC em Desenvolvimento', 'Desenvolvimento'), ('Aguardando Sessão Prévia', 'Previa'), ('Reprovado na Sessão Prévia', 'Reprovado Previa'), ('Aguardando Sessão Final', 'Final'), ('Reprovado na Sessão Final', 'Reprovado Final'), ('TCC em Fase de Ajuste', 'Ajuste'), ('TCC Aprovado', 'Aprovado')], max_length=255),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='autorizacaoPublicacao',
            field=models.FileField(blank=True, null=True, upload_to='tcc/autorizacaoPublicacao'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='dataInicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='documentoTCC',
            field=models.FileField(blank=True, null=True, upload_to='tcc/documento'),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='prazoEntregaFinal',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='prazoEntregaPrevia',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
