# Generated by Django 5.0.3 on 2024-04-22 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_banca_autorsugestao_alter_banca_professores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='configuracoes',
        ),
        migrations.DeleteModel(
            name='Configuracoes',
        ),
    ]
