# Generated by Django 5.0.3 on 2024-04-08 22:19

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_convite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracoes',
            name='dataAberturaPrazoPropostas',
        ),
        migrations.RemoveField(
            model_name='configuracoes',
            name='dataFechamentoPrazoPropostas',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='coordenador',
        ),
        migrations.AddField(
            model_name='semestre',
            name='dataAberturaPrazoPropostas',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.AddField(
            model_name='semestre',
            name='dataFechamentoPrazoPropostas',
            field=models.DateField(default=datetime.datetime.today),
        ),
        migrations.CreateModel(
            name='SemestreCoordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAlteracao', models.DateField(auto_now_add=True)),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.professorinterno')),
                ('semestre', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.semestre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
