# Generated by Django 5.0.3 on 2024-04-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_semestre_configuracoes_delete_configuracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
