# Generated by Django 4.2.6 on 2024-04-01 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_professorexterno_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TccStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PROPOSTA_ANALISE_ORIENTADOR', 'Proposta Analise Orientador'), ('PROPOSTA_RECUSADA_ORIENTADOR', 'Proposta Recusada Orientador'), ('PROPOSTA_ANALISE_COORDENADOR', 'Proposta Analise Coordenador'), ('PROPOSTA_RECUSADA_COORDENADOR', 'Proposta Recusada Coordenador'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('PREVIA', 'Previa'), ('REPROVADO_PREVIA', 'Reprovado Previa'), ('FINAL', 'Final'), ('REPROVADO_FINAL', 'Reprovado Final'), ('AJUSTE', 'Ajuste'), ('APROVADO', 'Aprovado')], max_length=255)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('dataStatus', models.DateTimeField(auto_now=True)),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.tcc')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='statustcc',
            name='tcc',
        ),
        migrations.DeleteModel(
            name='Convite',
        ),
        migrations.DeleteModel(
            name='StatusTCC',
        ),
    ]
