# Generated by Django 5.0.3 on 2025-01-21 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_superadmin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoCoordenadorCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de alteração')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_cursos_coordenados', to='app.professorinterno', verbose_name='Coordenador')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_coordenadores', to='app.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Histórico de Coordenadores por Curso',
                'verbose_name_plural': 'Histórico de Coordenadores por Curso',
            },
        ),
    ]
