# Generated by Django 4.2.6 on 2024-04-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tccstatus_remove_statustcc_tcc_delete_convite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConviteOrientacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aceito', models.BooleanField(default=False)),
                ('justificativa_recusa', models.TextField(blank=True, null=True)),
                ('data_convite', models.DateTimeField(auto_now_add=True)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.professor')),
                ('tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tcc')),
            ],
            options={
                'unique_together': {('professor', 'tcc')},
            },
        ),
    ]
