# Generated by Django 5.0.3 on 2025-01-24 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_historicocoordenadorcurso'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visibilidade do Curso'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordenadores', to='app.curso'),
        ),
    ]
