# Generated by Django 4.2.6 on 2024-04-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tccstatus_remove_statustcc_tcc_delete_convite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ficha_avaliacao',
            field=models.FileField(blank=True, null=True, upload_to='avaliacoes/fichas'),
        ),
    ]
