# Generated by Django 5.0.3 on 2024-04-24 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_usuario_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banca',
            name='professoresSugeridos',
        ),
        migrations.DeleteModel(
            name='BancaPrioridade',
        ),
    ]
