# Generated by Django 5.0.3 on 2024-04-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_banca_professoressugeridos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='validacaoCoordenador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banca',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='banca_professores', to='app.professor'),
        ),
    ]
