# Generated by Django 5.0.3 on 2025-02-01 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_curso_visible_alter_coordenador_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='dataAberturaPrazoPropostas',
        ),
        migrations.RemoveField(
            model_name='semestre',
            name='dataFechamentoPrazoPropostas',
        ),
        migrations.DeleteModel(
            name='SemestreCoordenador',
        ),
    ]
