# Generated by Django 5.0.3 on 2025-02-04 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_semestre_dataaberturaprazopropostas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professorexterno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professores_externos', to='app.curso'),
        ),
    ]
