# Generated by Django 5.0.3 on 2024-04-26 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sessao_validacaocoordenador_alter_banca_professores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessaofinal',
            name='avaliacao',
        ),
        migrations.AlterField(
            model_name='sessaofinal',
            name='sessao_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.sessao'),
        ),
    ]
