# Generated by Django 4.2.6 on 2024-04-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_avaliacao_ficha_avaliacao'),
        ('app', '0007_delete_conviteorientacao'),
    ]

    operations = [
    ]
