# Generated by Django 5.0.3 on 2025-02-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_professorexterno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='professores',
            field=models.ManyToManyField(related_name='cursos', to='app.professor', verbose_name='Professores associados ao curso'),
        ),
    ]
