# Generated by Django 5.0.3 on 2025-02-06 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_curso_professores'),
    ]

    operations = [
        migrations.AddField(
            model_name='tema',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='sugestoes', to='app.curso', verbose_name='Curso'),
        ),
    ]
