# Generated by Django 5.0.3 on 2025-02-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_tema_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='ficha_avaliacao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='tcc_definitivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='documentoTCCSessao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tcc',
            name='autorizacaoPublicacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
