# Generated by Django 5.0.3 on 2025-02-17 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_avaliacao_ficha_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banca',
            name='sessao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bancas', to='app.sessao'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='tcc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessoes', to='app.tcc'),
        ),
    ]
