# Generated by Django 5.0.3 on 2025-02-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_banca_sessao_alter_sessao_tcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tipo_avaliacao',
            field=models.CharField(choices=[('Avaliação de TCC do Curso de Análise e Desenvolvimento de Sistemas', 'Ads'), ('Não avaliar via sistema', 'None')], default='Avaliação de TCC do Curso de Análise e Desenvolvimento de Sistemas', max_length=100, verbose_name='Tipo de Avaliação'),
        ),
    ]
