# Generated by Django 5.0.3 on 2025-02-21 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_curso_tipo_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_avaliacao',
            field=models.CharField(choices=[('ADS', 'Avaliação de TCC do Curso de Análise e Desenvolvimento de Sistemas'), ('NONE', 'Não avaliar via sistema')], default='ADS', max_length=100, verbose_name='Tipo de Avaliação'),
        ),
    ]
