# Generated by Django 5.0.3 on 2025-02-21 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_curso_tipo_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo_avaliacao',
            field=models.CharField(choices=[('ADS', 'Ads'), ('NONE', 'None')], default='ADS', max_length=100, verbose_name='Tipo de Avaliação'),
        ),
    ]
