# Generated by Django 5.0.3 on 2025-02-21 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_curso_tipo_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='tipo_avaliacao',
        ),
    ]
